---
kind: pipeline
type: docker
name: send_fs_neo_org

platform:
  os: linux
  arch: amd64

steps:
- name: make prod tarball
  image: registry.nspcc.ru/docker-local/ui_builder:latest
  commands:
  - git fetch --tags
  - export PKGNAME=`make pkgname`
  - make build
  - curl -H "X-JFrog-Art-Api:$API_KEY" -T "$PKGNAME" "https://registry.nspcc.ru/artifactory/send.fs.neo.org/$PKGNAME"
  environment:
    API_KEY:
      from_secret: sami_api_key

trigger:
  branch:
  - master
  event:
  - push

image_pull_secrets:
- docker_auth

...
